server:
  port: 8080
  shutdown: graceful

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: "test"
            uri: http://localhost:8081/
            predicates:
              - Path=/test/**
            filters:
              - RewritePath=/test/(?<path>.*), /$\{path}
  threads:
    virtual:
      enabled: true